<?php
namespace SN\AnimeBundle\Entity;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * AnimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
 
class AnimeRepository extends EntityRepository
{
public function getAnimes($page, $nbPerPage)

  {

    $query = $this->createQueryBuilder('a')

      ->leftJoin('a.image', 'i')

      ->addSelect('i')

      

      ->orderBy('a.dateajout', 'DESC')

      ->getQuery()

    ;

    $query

      // On définit l'annonce à partir de laquelle commencer la liste

      ->setFirstResult(($page-1) * $nbPerPage)

      // Ainsi que le nombre d'annonce à afficher sur une page

      ->setMaxResults($nbPerPage)

    ;

    // Enfin, on retourne l'objet Paginator correspondant à la requête construite

    // (n'oubliez pas le use correspondant en début de fichier)

    return new Paginator($query, true);

  }
}
