<?php


namespace SN\AnimeBundle\Entity;


use Doctrine\ORM\EntityRepository;


/**
 * GenresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class GenresRepository extends EntityRepository

{
  
     
}
