<?php

namespace SN\AnimeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageanimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageanimeRepository extends EntityRepository
{
}
