<?php


namespace SN\SysNewsBundle\Entity;


use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class CommentRepository extends EntityRepository

{
 public function getComments($id, $page, $limit)
  {
    $query = $this->createQueryBuilder('c')->Join('c.news', 'n')->addSelect('n');
    $query->where($query->expr()->eq('c.news' , $id))->orderBy('c.date', 'DESC');
    $query->getQuery()->getResult();
    $query->setFirstResult(($page-1) * $limit)->setMaxResults($limit);
    return new Paginator($query, true);
  }
}
